server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sprintpro_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 200618665
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===================== JPA 配置（自动建表、自动SQL） =====================
  jpa:
    hibernate:
      ddl-auto: update  # 自动创建/更新表（超级重要）
    show-sql: true      # 控制台显示执行的SQL
    properties:
      hibernate:
        format_sql: true # 格式化SQL，好看易懂

logging:
  level:
    com.dong.springboot: debug