server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
spring:
  profiles:
    active: dev
  # 👇 👇 👇 只加这一段，解决文件太大报错
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB