server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

doubao:
  api-key: ark-5fd6b3c0-ab0f-48cb-90c9-33a4349184e0-d5dde
  endpoint-id: ep-20260505232416-lzf7d
  url: https://ark.cn-beijing.volces.com/api/v3/chat/completions